# Generated by Django 5.2.11 on 2026-02-07 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_key', models.CharField(db_index=True, max_length=255)),
                ('client_id', models.CharField(max_length=64)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pdf_key', 'user', 'client_id')},
            },
        ),
        migrations.CreateModel(
            name='ArrowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrow_items', to='epstein_ui.annotation')),
            ],
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('text', models.TextField(blank=True)),
                ('font_family', models.CharField(blank=True, max_length=255)),
                ('font_size', models.CharField(blank=True, max_length=32)),
                ('font_weight', models.CharField(blank=True, max_length=32)),
                ('font_style', models.CharField(blank=True, max_length=32)),
                ('font_kerning', models.CharField(blank=True, max_length=32)),
                ('font_feature_settings', models.CharField(blank=True, max_length=64)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('opacity', models.FloatField(default=1)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_items', to='epstein_ui.annotation')),
            ],
        ),
    ]
