# Generated by Django 4.2.28 on 2026-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epstein_ui', '0013_add_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the ban')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banned User',
                'verbose_name_plural': 'Banned Users',
            },
        ),
    ]
