# Generated by Django 4.2.28 on 2026-02-16 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epstein_ui', '0014_banneduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolanaWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solana_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solana Wallet',
                'verbose_name_plural': 'Solana Wallets',
            },
        ),
    ]
